### ISSUE TITLE
Find the Runner-Up Score!

### ISSUE THREAD

**Issue by Ritika457** [Ritika457/Hacktoberfest2021#16]

**Comment by tech-monika** [comment]
plz assign this to me

**Comment by tech-monika** [comment]
plz assign this to me

**Comment by tech-hima** [comment]
please assign this to me.

**Comment by tech-hima** [comment]
# Find the Runner-Up Score! in Python - 
if __name__ == '__main__':
    n = int(raw_input())
    arr = map(int, raw_input().split())
    # Find the Runner-Up Score! in Python - 
    print(sorted(list(set(arr)))[-2])

**Comment by tech-hima** [comment]
kindly merge it.
